version: "3.8"
services:
  homolog:
    env_file:
      - .env.homolog
    build:
      context: .
      dockerfile: Dockerfile
    container_name: faithpoint-frontend-homolog
    environment:
      - NODE_ENV=homolog
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - faithpoint-network
    depends_on:
      - faith-point-backend
    restart: on-failure

  faith-point-backend:
    image: faithpoint-backend:homolog
    container_name: faith-point-backend
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - API_PORT=${API_PORT}
      - API_SECRET=${API_SECRET}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_PATH=${LOG_PATH}
      - REDIS_HOST=faith-point-redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3308:3308"
    networks:
      - faithpoint-network
    restart: on-failure

  faith-point-redis:
    image: redis:alpine
    container_name: faith-point-redis
    ports:
      - "6379:6379"
    networks:
      - faithpoint-network
    restart: always

networks:
  faithpoint-network:
    driver: bridge
