version: "3.9"
services:
  production:
    env_file:
      - .env.production
    build:
      context: .
      dockerfile: Dockerfile
    container_name: faithpoint-frontend-production
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - faithpoint-network
    restart: on-failure

networks:
  faithpoint-network:
    driver: bridge
